### ISSUE TITLE
Move logic from client side to server side

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/AppStoreClient#26]
Right now AppStoreClient hides invisible stores and sorts applications on client side.

This is a very big issue for Polymer binding, as the bound objects are not the model objects.
In the result, when an error occurs, `dom-bind-notifier` notifies about the change, but it is not reflected to view.

I tried to find a workaround, but failed. Polymer just refuses to update view.

So, we have to move the logic to server side.

AppStoreServer should

- [ ] Return only visible stores.
- [ ] Return only latest available version of each app.
- [ ] Sort apps alphabetically.

@andwah, I guess this is on you, since I don't have required environment.

cc @warpech

**Comment by andwah** [comment]
I agree we should enhance the api with these features.

**Comment by andwah** [comment]
And also make the appstore retrive the app's from the appstore server directly, not as we do today via the Administrator.

**Comment by miyconst** [comment]
Agree, but it should be another issue.

**Comment by miyconst** [comment]
@warpech any progress on this?

**Comment by warpech** [comment]
As @andwah reported yesterday, there is a refactoring underway (on branch `next`). Can be seen here: https://github.com/StarcounterSamples/AppStoreClient/tree/next/src/AppStoreClient/wwwroot/AppStoreClient/viewmodels

@andwah can explain it in more details.

**Comment by andwah** [comment]
***Phase 1***
Change so the client is in direct contact with the Appstore server (still filtering logic,sorting on client).
At the moment this is almost done.

There is a big issues when apps is starting/stopping then the appstore client gui is not responding, due to the appstore client was restarted and the current session is closed by the server. 

I have not solution for this, anyone?

***Phase 2***
Move most of the sorting filtering etc. to the AppStore server when the *new* Appstore version is in place., this will be easy and fast to do.

**Comment by warpech** [comment]
> I have not solution for this, anyone?

This will be partially solved by https://github.com/Starcounter/Starcounter/issues/3084. When the server is restarted, the client will attempt reconnecting. After failed reconnection (session does not exist after restart), the client will display a modal asking to reload the page.

Then we have 2 choices:

1. add a JavaScript to AppStoreClient, who will listen to Puppet session error and reload the page (proposed by @miyconst). This is easy to achieve, though the UX will be far from seamless...
2. save sessions in the database, so that they can survive the restart (I think this will be hard to achieve)
